name: Build .NET API Image and Push to AWS Registry


on: 
  push
    
jobs:
  build-weather-forecast-api:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2

      - name: Login to Azure ACR
        uses: docker/login-action@v1
        with:
          registry: ${{secrets.AZURE_REGISTRY}}
          username: ${{secrets.SERVICE_PRINCIPAL_USERID}}
          password: ${{secrets.SERVICE_PRINCIPAL_PASSWORD}}
      
      - name: Build and push
        env:
          COMPOSE_DOCKER_CLI_BUILD: 1
          DOCKER_BUILDKIT: 1
          CONTEXT: .
          DOCKER_FILE: Dockerfile
          IMAGE: ${{secrets.AZURE_REGISTRY}}/weather-forecast-api:latest
        run: |
          docker build \
            --file ${DOCKER_FILE} \
            --tag ${IMAGE} \
            ${CONTEXT}
            docker push ${IMAGE}
      
      - name: Login to Azure
        uses: azure/login@v1  
        env:
          IMAGE: ${{secrets.AZURE_REGISTRY}}/weather-forecast-api:latest
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Deploy to Azure
        env:
          IMAGE: ${{secrets.AZURE_REGISTRY}}/weather-forecast-api:latest
        run: |
          az container create --resource-group private-app-registry --name weatherforecastapi --image ${IMAGE} --ports 80 443 --cpu 1 --memory 1 --registry-login-server ${{secrets.AZURE_REGISTRY}} --registry-username ${{secrets.SERVICE_PRINCIPAL_USERID}} --registry-password ${{secrets.SERVICE_PRINCIPAL_PASSWORD}}